"""create_quran_tables

Revision ID: 3030d67465a4
Revises: 1252150a6355
Create Date: 2026-03-17 00:43:21.888676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3030d67465a4'
down_revision: Union[str, Sequence[str], None] = '1252150a6355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_arabic', sa.String(length=100), nullable=False),
    sa.Column('name_english', sa.String(length=100), nullable=False),
    sa.Column('name_transliteration', sa.String(length=100), nullable=True),
    sa.Column('revelation_type', sa.String(length=20), nullable=True),
    sa.Column('total_ayahs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surahs_number'), 'surahs', ['number'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arabic', sa.Text(), nullable=False),
    sa.Column('arabic_clean', sa.String(length=200), nullable=False),
    sa.Column('translation_ru', sa.Text(), nullable=True),
    sa.Column('translation_en', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_arabic_clean'), 'words', ['arabic_clean'], unique=True)
    op.create_table('ayahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('global_number', sa.Integer(), nullable=False),
    sa.Column('juz_number', sa.Integer(), nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=False),
    sa.Column('russian_translation', sa.Text(), nullable=True),
    sa.Column('english_translation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['surah_number'], ['surahs.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_number'),
    sa.UniqueConstraint('surah_number', 'ayah_number', name='uq_ayah')
    )
    op.create_index(op.f('ix_ayahs_surah_number'), 'ayahs', ['surah_number'], unique=False)
    op.create_table('word_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'ayah_id', 'position', name='uq_word_occurrence')
    )
    op.create_index(op.f('ix_word_occurrences_ayah_id'), 'word_occurrences', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_word_occurrences_word_id'), 'word_occurrences', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_occurrences_word_id'), table_name='word_occurrences')
    op.drop_index(op.f('ix_word_occurrences_ayah_id'), table_name='word_occurrences')
    op.drop_table('word_occurrences')
    op.drop_index(op.f('ix_ayahs_surah_number'), table_name='ayahs')
    op.drop_table('ayahs')
    op.drop_index(op.f('ix_words_arabic_clean'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_surahs_number'), table_name='surahs')
    op.drop_table('surahs')
    # ### end Alembic commands ###
