"""create_flashcard_tables

Revision ID: 8bf7dca26d2a
Revises: 8ffcfa14a4a9
Create Date: 2026-03-17 01:02:19.624150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf7dca26d2a'
down_revision: Union[str, Sequence[str], None] = '8ffcfa14a4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('cards_correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_sessions_user_id'), 'review_sessions', ['user_id'], unique=False)
    op.create_table('user_card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index(op.f('ix_user_card_progress_next_review_date'), 'user_card_progress', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_user_card_progress_user_id'), 'user_card_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_card_progress_word_id'), 'user_card_progress', ['word_id'], unique=False)
    op.create_table('card_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['user_card_progress.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_reviews_progress_id'), 'card_reviews', ['progress_id'], unique=False)
    op.create_index(op.f('ix_card_reviews_session_id'), 'card_reviews', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_reviews_session_id'), table_name='card_reviews')
    op.drop_index(op.f('ix_card_reviews_progress_id'), table_name='card_reviews')
    op.drop_table('card_reviews')
    op.drop_index(op.f('ix_user_card_progress_word_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_user_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_next_review_date'), table_name='user_card_progress')
    op.drop_table('user_card_progress')
    op.drop_index(op.f('ix_review_sessions_user_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    # ### end Alembic commands ###
